@startuml

object Tinder
object Match
object Like
object Dismiss
object Swipe
object Candidates
object User
note right
User is the human
Profile represents the user (Could be fake)
end note
object Profile
object Name
object Conversation

User ..> Swipe
User *--> Profile

Tinder *--> "2..n" User
Profile *--> Name

Like -up-|> Swipe
Dismiss -up-|> Swipe
Candidates "0..n" o-down-> Profile

Profile ..> Candidates
Conversation --> Match

Swipe --> Profile
Match *--> "2" Profile
Match <--> "2" Like

User --> Conversation

@enduml