@startuml GetProfileSpecification

title GetProfileSpecification

state IN_APP
state SWIPE
state CONVERSATION
state PROFILE
state WAITING_PROFILE as " "

IN_APP --> WAITING_PROFILE
SWIPE --> WAITING_PROFILE
CONVERSATION --> WAITING_PROFILE: User requests a profile
WAITING_PROFILE --> PROFILE: System shows the requested profile


@enduml