@startuml

state SWIPPING
state PROFILE_LIKED
state SHOW_MATCH_CREATED
state is_match <<choice>>

[*] --> SWIPPING
SWIPPING --> PROFILE_LIKED: User create a like
PROFILE_LIKED --> is_match
is_match --> SHOW_MATCH_CREATED: is match
is_match --> SWIPPING: not match
SHOW_MATCH_CREATED --> SWIPPING

@enduml