@startuml

state CONVERSATION
state PROFILE
state READING_PROFILE as " "


[*] --> CONVERSATION
CONVERSATION --> READING_PROFILE: User request to read a profile
READING_PROFILE --> PROFILE: System allows to read a profile

PROFILE --> [*]


@enduml