@startuml

state CONVERSATION
state PROFILE
state STATE_1

[*] --> CONVERSATION 
CONVERSATION --> STATE_1 : User requires to open a profile
STATE_1 --> PROFILE : System shows the profile

PROFILE  --> [*]


@enduml