@startuml

state SWIPPING
state STATE_1 as " "
state SHOW_MATCH_CREATED as " "
state hasMoreProfiles <<choice>>
state SWIPPING_OUT as "SWIPPING"
state IN_APP
state isMatch <<choice>>


[*] --> SWIPPING
SWIPPING --> STATE_1: System requires a like
STATE_1 --> isMatch : User swipes 
hasMoreProfiles --> SWIPPING_OUT
hasMoreProfiles --> IN_APP: has no more profiles
isMatch --> SHOW_MATCH_CREATED: [match] System shows the match
isMatch --> hasMoreProfiles: [no match]
SHOW_MATCH_CREATED -->  hasMoreProfiles: System allows OpenConversation


@enduml