@startuml
left to right direction

actor User

usecase Login
usecase Swipe
usecase CreateUser
usecase CreateProfile

usecase GetProfile
usecase DeleteProfile
usecase StartSwiping
usecase SendMessage
usecase GetMatches

usecase EditProfile
usecase StartSwiping
usecase SendMessage
usecase OpenConversation

User --> CreateUser
CreateUser ..> CreateProfile: extends
User --> DeleteProfile
User --> EditProfile
User --> GetProfile
User --> SendMessage
User --> OpenConversation
User --> GetMatches
User --> StartSwiping
User --> Swipe

DeleteProfile --> Login: includes
EditProfile --> Login: includes
GetProfile --> Login: includes
SendMessage --> Login: includes
OpenConversation --> Login: includes
GetMatches --> Login: includes
StartSwiping --> Login: includes
Swipe --> Login: includes

@enduml