@startuml
left to right direction

actor User

usecase Login
usecase CreateProfile 
usecase GetProfile 
usecase DeleteProfile 
usecase Swipe
usecase GetMatches

usecase EditProfile 
usecase StartSwipping
usecase SendMessage
usecase OpenConversation

User --> Login
User --> CreateProfile
User --> DeleteProfile
User --> EditProfile
User --> GetProfile
User --> SendMessage
User --> OpenConversation
User --> GetMatches
User --> StartSwipping
User --> Swipe



@enduml