@startuml
left to right direction

actor User

usecase CreateProfile as "Create profile"
usecase Lookup
usecase Like
usecase Dismiss

User --> CreateProfile
User --> Lookup
Lookup ..> Like
Lookup ..> Dismiss


@enduml